import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const p = await b.newPage({ viewport: { width: 1000, height: 820 } })
await p.goto('http://localhost:4173', { waitUntil: 'networkidle' })
const skip = p.getByText('건너뛰기'); if (await skip.isVisible().catch(()=>false)) await skip.click()
await p.getByRole('textbox', { name: '조추첨 시드' }).fill('HEAT')
await p.getByText('시드로 즉시 조추첨').click()
await p.getByText('조추첨이 완료되었습니다', { exact:false }).waitFor({ timeout:8000 })
await p.getByRole('tab', { name: '조별리그' }).click()
await p.waitForTimeout(700)
await p.getByLabel('설정 열기').click()
await p.waitForTimeout(300)
await p.screenshot({ path: 'shot-groups.png' })
await b.close(); console.log('shot done')
