import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const p = await b.newPage({ viewport: { width: 1000, height: 900 } })
await p.goto('http://localhost:4173', { waitUntil: 'networkidle' })
const skip = p.getByText('건너뛰기'); if (await skip.isVisible().catch(()=>false)) await skip.click()
// apply violet skin via settings
await p.getByLabel('설정 열기').click(); await p.waitForTimeout(200)
await p.getByLabel('바이올렛').click(); await p.waitForTimeout(200)
await p.keyboard.press('Escape')
await p.getByRole('textbox', { name: '조추첨 시드' }).fill('MAP')
await p.getByText('시드로 즉시 조추첨').click()
await p.getByText('조추첨이 완료되었습니다', { exact:false }).waitFor({ timeout:8000 })
await p.getByRole('tab', { name: '일정 진행' }).click()
await p.waitForTimeout(600)
await p.getByText('개최 도시 지도', { exact:false }).click()
await p.waitForTimeout(400)
await p.screenshot({ path: 'shot-map.png' })
await b.close(); console.log('shot done')
